Simulation and Modeling Lab  
**Course Code:** CSE 413  
**Name:** Shoeb Sardar  
**ID:** 0432310005101066  
**Sec:** 7B1; **Batch:** 53   
**Semester:** Spring 2026  
**Assignment No.:** 02  

#📘 Individualized Student Task: Unique Matrix Value Investigation  
🎯 **Objective**  
To analyze how changing matrix values affects matrix properties, using a student-specific matrix.

🧩 Task Rules (Important)  
👉 Each student must use a different matrix generated from their own ID.  

📝 **Task Description**  
**1. Create Your Personal Matrix**
Let:  
● d1 = last digit of your student ID  
● d2 = second last digit of your student ID  
Create the matrix:  

**2. Analyze Matrix A**  
Using NumPy, compute:  
● Shape of A  
● Determinant  
● Rank  
● Eigenvalues  
● Inverse (only if determinant ≠ 0)  

**3. Value Change Experiment**  
Create a new matrix B by changing exactly one value in A:  
● Add +1 to one element of your choice  
● You must clearly state which element you changed  

**4. Re-analyze Matrix B**  
Compute the same properties as in Step 2.  

**5. Comparison & Explanation**  
Answer the following in your own words:  
1. How did the determinant change and why?  
2. Did the rank change? Explain.  
3. How did the eigenvalues respond to the value change?  
4. Is B easier or harder to invert than A? Why?  

# Necessary Libraries

In [11]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# 1. Creating Personal Matrix as A

In [12]:
# ID Matrix
d1 = 6
d2 = 6

A = np.array([[d1+2, d2+1],[2*d1, d2+2]])

# Show Matrix
print("Matrix A: \n",A,"\n")


Matrix A: 
 [[ 8  7]
 [12  8]] 



# 2. Analyze Matrix A

In [13]:
# Shape of A
size_A = A.shape

# Determinant
det_A = np.linalg.det(A)

# Rank
rank_A = np.linalg.matrix_rank(A)

# Eigenvalues
eigenvalA = np.linalg.eigvals(A)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(A) != 0:
    inv_A = np.linalg.inv(A)
else:
    inv_A = "Matrix is singular, cannot compute inverse"

# Display results
print("Shape of A:", size_A,"\n")
print("Determinant of A:", det_A,"\n")
print("Rank of A:", rank_A,"\n")
print("Eigenvalues of A:", eigenvalA,"\n")
print("Inverse of A:\n", inv_A,"\n")

Shape of A: (2, 2) 

Determinant of A: -20.000000000000007 

Rank of A: 2 

Eigenvalues of A: [17.16515139 -1.16515139] 

Inverse of A:
 [[-0.4   0.35]
 [ 0.6  -0.4 ]] 



# 3. Value Change Experiment

In [14]:
# New Matrix B
B = np.array([[d1+2, d2+1],[2*d1, d2-2]]) # 4th element as d2-2 instead of d2+2

# Show Matrix
print("Matrix B:\n",B,"\n")

Matrix B:
 [[ 8  7]
 [12  4]] 



# 4. Re-analyze Matrix B

In [15]:
# Shape of B
size_B = B.shape

# Determinant
det_B = np.linalg.det(B)

# Rank
rank_B = np.linalg.matrix_rank(B)

# Eigenvalues
eigenvalB = np.linalg.eigvals(B)

# Inverse (only if determinant ≠ 0)
if np.linalg.det(B) != 0:
    inv_B = np.linalg.inv(B)
else:
    inv_B = "Matrix is singular, cannot compute inverse"

# Display results
print("Shape of B:", size_B,"\n")
print("Determinant of B:", det_B,"\n")
print("Rank of B:", rank_B,"\n")
print("Eigenvalues of B:", eigenvalB,"\n")
print("Inverse of B:\n", inv_B,"\n")

Shape of B: (2, 2) 

Determinant of B: -52.00000000000001 

Rank of B: 2 

Eigenvalues of B: [15.38083152 -3.38083152] 

Inverse of B:
 [[-0.07692308  0.13461538]
 [ 0.23076923 -0.15384615]] 



# 5. Comparison & Explanation

**Q1. How did the determinant change and why?**  
A: For a 2×2 matrix, determinant = ad − bc.  
  
      Det(A) = (8×8) − (7×12) = 64 − 84 = −20
      Det(B) = (8×4) − (7×12) = 32 − 84 = −52

The determinant became more negative (from −20 to −52).
This happened because we reduced one diagonal value, which lowered the product of the main diagonal (ad). Since the determinant depends directly on these products, changing one value caused a noticeable difference.  
  
  
**Q2. Did the rank change? Explain.**  
A: No, the rank did not change. Both matrices still have non-zero determinants, which means both are full rank (rank = 2). Since neither determinant is zero, the rank remains the same.  
  
  
**Q3. How did the eigenvalues respond to the value change?**  
A: The eigenvalues changed because both the determinant and the trace (sum of diagonal elements) changed. When we decreased one diagonal element, the trace became smaller and the determinant changed significantly. Since eigenvalues are calculated using these values, they shifted accordingly.  


**Q4. Is B easier or harder to invert than A? Why?**  
A: B is slightly easier to invert. This is because B has a larger absolute determinant (|−52|) compared to A (|−20|). A larger determinant generally means the matrix is farther from zero and more stable when finding the inverse.